newsletter_subscribe:
  path: /newsletter-subscribe
  controller: Greeflas\Bundle\NewsletterBundle\Controller\DefaultController::subscribe
  methods: [POST]

xhr_newsletter_subscribe:
  path: /xhr-newsletter-subscribe
  controller: Greeflas\Bundle\NewsletterBundle\Controller\AjaxController::subscribe
  methods: [POST]
